spring:
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/test16
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: lalli.c22@gmail.com
    password: lallinari@123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
           enable: true
          
    
    
   